name: Mabl Test Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mabl-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js (si tu flujo requiere Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'


      # 5. Instalar Mabl CLI usando snap
      - name: Install Mabl CLI
        run: |
           curl -s https://cli.mabl.com/download/cli/install.sh -o install.sh
           bash install.sh

      # 6. Ejecutar Mabl en modo headless usando xvfb
      - name: Run Mabl tests
        run: |
          export PATH="/snap/bin:$PATH"
          xvfb-run mabl-app login --api-token ${{ secrets.MABL_API_TOKEN }}
          xvfb-run mabl-app test run --environment <ID del entorno> --test <ID del test>
