name: Mabl Test Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mabl-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js (si tu flujo requiere Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # 3. Instalar Mabl CLI usando el script de instalación
      - name: Install Mabl CLI
        run: |
          # Descargar e instalar Mabl CLI
          curl -s https://cli.mabl.com/download/cli/install.sh | bash
          
          # Asegurarse de que el binario de Mabl esté en el PATH
          export PATH="$HOME/.mabl/bin:$PATH"
          
          # Verificar que Mabl está accesible
          mabl --version

      # 4. Ejecutar los tests en Mabl
      - name: Run Mabl tests
        run: |
          export PATH="$HOME/.mabl/bin:$PATH"
          mabl login --api-token ${{ secrets.MABL_API_TOKEN }}
          mabl test run --environment <ID del entorno> --test <ID del test>
