name: Mabl Test Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mabl-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js (si tu flujo requiere Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # 3. Instalar Mabl CLI usando snap
      - name: Install Mabl CLI
        run: |
          # Instalar Mabl CLI usando snap
          sudo snap install mabl-app --classic
          
          # Asegurarse de que /snap/bin esté en el PATH
          export PATH="/snap/bin:$PATH"
          
          # Verificar que Mabl está accesible
          mabl-app --version

      # 4. Ejecutar los tests en Mabl
      - name: Run Mabl tests
        run: |
          export PATH="/snap/bin:$PATH"
          mabl-app login --api-token ${{ secrets.MABL_API_TOKEN }}
          mabl-app test run --environment <ID del entorno> --test <ID del test>
