name: Mabl Test Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mabl-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Verificar la conectividad de red
      - name: Check network connectivity to Mabl
        run: |
          ping -c 3 cli.mabl.com || true
          curl -I https://cli.mabl.com || true

      # 3. Configurar DNS alternativo
      - name: Set up DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
          echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null

      # 4. Descargar e instalar Mabl CLI manualmente
      - name: Install Mabl CLI
        run: |
          echo "Descargando Mabl CLI..."
          curl -LO https://cli.mabl.com/download/latest/linux/mabl
          
          # Hacer que el binario sea ejecutable
          chmod +x mabl
          
          # Mover el binario a un directorio en el PATH
          sudo mv mabl /usr/local/bin/mabl
          
          # Verificar que Mabl está accesible
          mabl --version

      # 5. Ejecutar los tests en Mabl
      - name: Run Mabl tests
        run: |
          mabl login --api-token ${{ secrets.MABL_API_TOKEN }}
          mabl test run --environment <ID del entorno> --test <ID del test>
